# FUNDAMENTOS DE PROGRAMACIÓN PARA INGENIERÍA/FUNDAMENTOS DE COMPUTACIÓN Y PROGRAMACIÓN
# SECCIÓN DEL CURSO: 
# PROFESOR DE TEORÍA: 
# PROFESOR DE LABORATORIO: 
#
# AUTOR
# NOMBRE: 
# RUT: 
# CARRERA: 

# Escriba su código a continuación

print("hello world.")